my_dbt_project:
  target: local
  outputs:
    local:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: "SANDBOX"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "BEN"
      client_session_keep_alive: False
